### ISSUE TITLE
Urls with parentheses fail

### ISSUE THREAD

**Issue by chuckhendo** [website-scraper/node-css-url-parser#20]
Something like `url('test(1).png')` fails to parse correctly. Since Javascript doesn't support recursive regex, it seems the only option is to find a solution that doesn't use regex. Would you be open to a PR that no longer uses regex to match (and would fix this issue)

**Comment by s0ph1e** [comment]
Hi @chuckhendo
Thanks for reporting issue
PRs are welcome :)

**Comment by s0ph1e** [comment]
Fix is released in version `1.1.3`
