### ISSUE TITLE
Accept a file as input

### ISSUE THREAD

**Issue by gemal** [website-scraper/node-css-url-parser#35]
could be cool if I could just pass a file as input instead of file content

**Comment by s0ph1e** [comment]
Hi @gemal! Thank you for suggestion

The idea of this module is to be as simple as possible. If we add file input - it will require to make this module asynchronous and implement reading from file system - which may be quite complex. 

I'm not going to do implement it in this module. Feel free to create new module which will handle FS stuff and reuse `css-url-parser` there.
